export const GET_FORMATIONS_LOAD="GET_FORMATIONS_LOAD";
export const GET_FORMATIONS_SUCCES="GET_FORMATIONS_SUCCES";
export const GET_FORMATIONS_FAILED="GET_FORMATIONS_FAILED";
export const DELETE_FORMATION = "DELETE_FORMATION"; 